import{S as c,i as l}from"./assets/vendor-8c59ed88.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function s(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(e){if(e.ep)return;e.ep=!0;const r=s(e);fetch(e.href,r)}})();function d(t){const o="https://pixabay.com/api/",s=new URLSearchParams({key:"44049437-ef12fae0346c4a67068c57c01",q:t,image_type:"photo",orientation:"horizontal",safesearch:!0}),i=`${o}?${s}`;return fetch(i).then(e=>e.json())}function u(t){return`<li><a href="${t.largeImageURL}"><img
    src="${t.webformatURL}" alt="${t.tags}"/></a>
    <div><h3>Likes</h3><p>${t.likes}</p></div>
    <div><h3>Views</h3><p>${t.views}</p></div>
    <div><h3>Comments</h3><p>${t.comments}</p></div>
    <div><h3>Downloads</h3><p>${t.downloads}</p></div>
    
  </li>`}function p(t){return t.map(u).join("")}const m=new c(".gallery a",{animationSpeed:200,animationSlide:!0,disableScroll:!1,history:!1,captionsData:"alt",captionDelay:250}),f=document.querySelector(".form"),h=document.querySelector(".gallery"),n=document.querySelector(".loader");f.addEventListener("submit",async t=>{t.preventDefault();const o=t.target.elements.word.value.trim();if(!o){l.error({title:"Error",message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight"});return}n.classList.remove("hidden"),n.style.display="block",d(o).then(s=>{const i=p(s.hits);h.innerHTML=i,m.refresh(),n.classList.add("hidden"),n.style.display="none"}).catch(s=>{console.error("Error searching images:",s.message),n.classList.add("hidden"),n.style.display="none"})});
//# sourceMappingURL=commonHelpers.js.map
